name: Continuous Integration
on:
  push:
    branches: [main]
  pull_request:

jobs:
  scalafmt:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./bin/scalafmt --test
  cross-compilation:
    name: Cross Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: coursier/setup-action@v1.3.3
        with:
          apps: sbt
      - run: sbt +Test/compile
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            jvm: 'adoptium:1.8.0-372'
          - os: window-latest
            jvm: 'adoptium:1.11.0.20+8'
          - os: macOS-latest
            jvm: 'adoptium:1.17.0.7'
          - os: ubuntu-latest
            jvm: 'adoptium:1.20.0.1'
    name: Unit Tests on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: coursier/setup-action@v1.3.3
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt
    - name: Unit tests
      run: sbt test
      shell: bash
  scripted-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            jvm: 'adoptium:1.8.0-372'
          - os: unbutu-latest
            jvm: 'adoptium:1.11.0.20+8'
          - os: macOS-latest
            jvm: 'adoptium:1.17.0.7'
    name: Scripted Tests on ${{ matrix.os }} -- ${{ matrix.jvm }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: coursier/setup-action@v1.3.3
      with:
        jvm: ${{ matrix.jvm }}
        apps: sbt
    - name: Scripted tests
      run: sbt sbtPlugin/scripted
      shell: bash
