name: Dependency Graph
on:
  push:
    branches:
      - main
jobs:
  submit:
    name: Submit
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: scalacenter/sbt-dependency-graph-action@v0.1.0-M2
        with:
          scala-versions: 2.12.16 2.13.8 3.1.3
